export const comments = [
  {
    commentId: 1,
    postId: 1,
    userId: 1,
    nickname: "user1",
    profile_image: "http://localhost:8000/images/profile/zzanggu.png",
    comment:
      "공무원은 국민전체에 대한 봉사자이며, 국민에 대하여 책임을 진다. 국무총리는 대통령을 보좌하며, 행정에 관하여 대통령의 명을 받아 행정각부를 통할한다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 2,
    postId: 2,
    userId: 1,
    nickname: "user1",
    profile_image: "http://localhost:8000/images/profile/zzanggu.png",
    comment:
      "중앙선거관리위원회는 법령의 범위안에서 선거관리·국민투표관리 또는 정당사무에 관한 규칙을 제정할 수 있으며, 법률에 저촉되지 아니하는 범위안에서 내부규율에 관한 규칙을 제정할 수 있다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 3,
    postId: 3,
    userId: 2,
    nickname: "user2",
    profile_image: "http://localhost:8000/images/profile/suzi.jpeg",
    comment:
      "대통령으로 선거될 수 있는 자는 국회의원의 피선거권이 있고 선거일 현재 40세에 달하여야 한다. 국가는 법률이 정하는 바에 의하여 재외국민을 보호할 의무를 진다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 4,
    postId: 4,
    userId: 2,
    nickname: "user2",
    profile_image: "http://localhost:8000/images/profile/suzi.jpeg",
    comment:
      "국민의 모든 자유와 권리는 국가안전보장·질서유지 또는 공공복리를 위하여 필요한 경우에 한하여 법률로써 제한할 수 있으며, 제한하는 경우에도 자유와 권리의 본질적인 내용을 침해할 수 없다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 5,
    postId: 5,
    userId: 3,
    nickname: "user3",
    profile_image: "http://localhost:8000/images/profile/chulsoo.jpeg",
    comment:
      "국가는 지역간의 균형있는 발전을 위하여 지역경제를 육성할 의무를 진다. 국회에서 의결된 법률안은 정부에 이송되어 15일 이내에 대통령이 공포한다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 6,
    postId: 6,
    userId: 3,
    nickname: "user3",
    profile_image: "http://localhost:8000/images/profile/chulsoo.jpeg",
    comment:
      "국방상 또는 국민경제상 긴절한 필요로 인하여 법률이 정하는 경우를 제외하고는, 사영기업을 국유 또는 공유로 이전하거나 그 경영을 통제 또는 관리할 수 없다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 7,
    postId: 7,
    userId: 4,
    nickname: "user4",
    profile_image: "http://localhost:8000/images/profile/hunyi.webp",
    comment:
      "국가안전보장회의의 조직·직무범위 기타 필요한 사항은 법률로 정한다. 모든 국민은 신속한 재판을 받을 권리를 가진다. 형사피고인은 상당한 이유가 없는 한 지체없이 공개재판을 받을 권리를 가진다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 8,
    postId: 8,
    userId: 4,
    nickname: "user4",
    profile_image: "http://localhost:8000/images/profile/hunyi.webp",
    comment:
      "국회의원은 현행범인인 경우를 제외하고는 회기중 국회의 동의없이 체포 또는 구금되지 아니한다. 헌법재판소는 법관의 자격을 가진 9인의 재판관으로 구성하며, 재판관은 대통령이 임명한다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 9,
    postId: 9,
    userId: 5,
    nickname: "user5",
    profile_image: "http://localhost:8000/images/profile/yuri.jpeg",
    comment:
      "모든 국민은 헌법과 법률이 정한 법관에 의하여 법률에 의한 재판을 받을 권리를 가진다. 헌법재판소의 조직과 운영 기타 필요한 사항은 법률로 정한다",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    commentId: 10,
    postId: 10,
    userId: 5,
    nickname: "user5",
    profile_image: "http://localhost:8000/images/profile/yuri.jpeg",
    comment:
      "재의의 요구가 있을 때에는 국회는 재의에 붙이고, 재적의원과반수의 출석과 출석의원 3분의 2 이상의 찬성으로 전과 같은 의결을 하면 그 법률안은 법률로서 확정된다.",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
];

export const posts = [
  {
    postId: 1,
    userId: 1,
    nickname: "user1",
    userImage: "http://localhost:8000/images/profile/zzanggu.png",
    title:
      "대법원에 대법관을 둔다. 다만, 법률이 정하는 바에 의하여 대법관이 아닌 법관을 둘 수 있다.",
    content:
      "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 19000,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 2,
    userId: 1,
    nickname: "user1",
    userImage: "http://localhost:8000/images/profile/zzanggu.png",
    title: "헌법재판소의 조직과 운영 기타 필요한 사항은 법률로 정한다.",
    content:
      "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 1000,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 3,
    userId: 2,
    nickname: "user2",
    userImage: "http://localhost:8000/images/profile/suzi.jpeg",
    title:
      "모든 국민은 양심의 자유를 가진다. 대통령은 취임에 즈음하여 다음의 선서를 한다.",
    content:
      "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 10000,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 4,
    userId: 2,
    nickname: "user2",
    userImage: "http://localhost:8000/images/profile/suzi.jpeg",
    title: "공무원은 국민전체에 대한 봉사자이며, 국민에 대하여 책임을 진다.",
    content:
      "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 30,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 5,
    userId: 3,
    nickname: "user3",
    userImage: "http://localhost:8000/images/profile/chulsoo.jpeg",
    title:
      "국정의 중요한 사항에 관한 대통령의 자문에 응하기 위하여 국가원로로 구성되는 국가원로자문회의를 둘 수 있다.",
    content:
      "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 30,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 6,
    userId: 3,
    nickname: "user3",
    userImage: "http://localhost:8000/images/profile/chulsoo.jpeg",
    title:
      "대통령이 궐위되거나 사고로 인하여 직무를 수행할 수 없을 때에는 국무총리, 법률이 정한 국무위원의 순서로 그 권한을 대행한다.",
    content:
      "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 30,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 7,
    userId: 4,
    nickname: "user4",
    userImage: "http://localhost:8000/images/profile/hunyi.webp",
    title:
      "국회는 국민의 보통·평등·직접·비밀선거에 의하여 선출된 국회의원으로 구성한다.",
    content:
      "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 10000,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 8,
    userId: 4,
    nickname: "user4",
    userImage: "http://localhost:8000/images/profile/hunyi.webp",
    title:
      "국무위원은 국정에 관하여 대통령을 보좌하며, 국무회의의 구성원으로서 국정을 심의한다.",
    content:
      "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 10,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 9,
    userId: 5,
    nickname: "user5",
    userImage: "http://localhost:8000/images/profile/yuri.jpeg",
    title:
      "국회의원은 국회에서 직무상 행한 발언과 표결에 관하여 국회외에서 책임을 지지 아니한다.",
    content:
      "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 30,
    like: 12,
    comment_count: 1,
  },
  {
    postId: 10,
    userId: 5,
    nickname: "user5",
    userImage: "http://localhost:8000/images/profile/yuri.jpeg",
    title:
      "국민의 자유와 권리는 헌법에 열거되지 아니한 이유로 경시되지 아니한다.",
    content:
      "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error",
    postImage: "/images/postImage.jpg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
    view: 30,
    like: 12,
    comment_count: 1,
  },
];

export const users = [
  {
    userId: 1,
    nickname: "user1",
    email: "user1@example.com",
    password: "user1",
    profile_image: "http://localhost:8000/images/profile/zzanggu.png",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    userId: 2,
    nickname: "user2",
    email: "user2@example.com",
    password: "user2",
    profile_image: "http://localhost:8000/images/profile/suzi.jpeg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    userId: 3,
    nickname: "user3",
    email: "user3@example.com",
    password: "user3",
    profile_image: "http://localhost:8000/images/profile/chulsoo.jpeg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    userId: 4,
    nickname: "user4",
    email: "user4@example.com",
    password: "user4",
    profile_image: "http://localhost:8000/images/profile/hunyi.webp",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
  {
    userId: 5,
    nickname: "user5",
    email: "user5@example.com",
    password: "user5",
    profile_image: "http://localhost:8000/images/profile/yuri.jpeg",
    created_at: "2024-04-04 00:00:00",
    updated_at: "2024-04-04 00:00:00",
    deleted_at: null,
  },
];
